spring:
  datasource:
    mssql:
      jdbc-url: jdbc:sqlserver://localhost:1700;databaseName=TestDB
      username : sa
      password : "<YourStrong!Passw0rd>"
      driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
      #driver-class-name : com.microsoft.sqlserver.jdbc.SQLServerDriver
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:49161:XE
      username: system
      password: oracle

